:score: _
:stem: latexmath
= current-sharing

This project aims to be fully complete in a command-line format and then transferred to a application framework (either a web GUI with Flask/Django/etc. or a software-based GUI with WxPython, etc.?)

== Installation

Instructions for this will be updated when the project is complete 

== Methods

=== currentSharing{score}general

Jump to functions and their details below:

<<current_sharing_numeric,current_sharing_numeric>> +
<<current_sharing_symbolic,current_sharing_symbolic>> +
<<valid_layer_list,valid_layer_list>> +
<<primary_current_identity,primary_current_identity>> +
<<traverse_layer_list,traverse_layer_list>> +
<<I_node,I_node>> +

==== _current{score}sharing{score}numeric_ [[id,current_sharing_numeric]]
Evaluates current sharing within the specified layer structure & dimensions.

*Parameters*:

[source,python]
----
n = int 
# Total layer number.

pl = list 
# A valid layer list representing the primary winding.

sl = list 
#  A valid layer list representing the secondary winding. Elements in the sl should not be in the pl.

b = float 
# Layer width (m)

f = int 
# Operating frequency (Hz)

l = float
# Turn length (m)

r = float or list(float) 
# Distances between layers (m). Can either be a single value (in which case distances are assumed to be the same) or a list of floats with N-1 entries.

Ip = float 
# Primary current value (A). If it is not specified, will be set to 1.

N_turns = list(int)
# Number of turns of each layer. Should have N entries. If not specified, all layers will be assumed to have 1 layer each.
----

*Returns*:
``X``

A 3×N by 1 vector, with the first N entries representing the current in layers 1 through N, and the next 2×N entries representing the surface current densities in each layer (starting from the top of the structure and moving down).

'''

==== _current{score}sharing{score}symbolic_ [[id,current_sharing_symbolic]]
Evaluates current sharing within the specified layer structure & dimensions.

*Parameters*:

[source,python]
----
n = int 
# Total layer number.

pl = list 
# A valid layer list representing the primary winding.

sl = list 
#  A valid layer list representing the secondary winding. Elements in the sl should not be in the pl.

N_turns = list(int)
# Number of turns of each layer. Should have N entries. If not specified, all layers will be assumed to have 1 layer each.

distanceFlag = bool
# 0 if all interlayer distances should be treated as the same. 1 otherwise.
----

*Returns*:
``X``

A 3×N by 1 vector, with the first N entries representing the current in layers 1 through N, and the next 2×N entries representing the surface current densities in each layer (starting from the top of the structure and moving down).

'''

==== _valid{score}layer{score}list_ [[id,valid_layer_list]]

*Parameters*:

[source,python]
----
node = int or list
# A potential layer list.

N = int
#  Total number of layers.
----

*Returns*:
``1`` if the layer list is valid, and ``0`` if it is not valid. A valid layer list can have three acceptable entries: an integer (of value between 1 and N inclusive), a series list ``(['s',  valid list, valid list])``, or a parallel list ``(['p', valid list, valid list])``.

'''

==== _primary{score}current{score}identity_ [[id,primary_current_identity]]

*Parameters*:

[source,python]
----
node = int or list
# A valid layer list or layer number

N = int
#  Total number of layers.
----

*Returns*:
``identity`` 

A list representing a primary current equality, with the left hand side of the equality implied to be nonzero.

'''

==== _traverse{score}layer{score}list_ [[id,traverse_layer_list]]

Returns a list of lists, with each inner list representing either a Faraday loop between paralleled layers or a series current identity between series connected layers.

*Parameters*:

[source,python]
----
node = int or list
# A valid layer list or layer number.

N = int
# Total number of layers.

d = float
# Skin depth

bOverL = float
# Ratio of layer width to turn length.

R = float or float list
# Distances between layers. Can either be a single value (in which case distances are assumed to be the same) or a list of floats with N-1 entries.

N_turns = int list
# Number of turns of each layer. Should have N entries. If not specified, all layers will be assumed to have 1 layer each.

array = list
# Top level calls should pass in an empty list.
----

*Returns*:
``array`` 

A list of lists, with each inner list representing either a Faraday loop between paralleled layers or a series current identity between series connected layers.

'''

==== _I{score}node_ [[id,I_node]]

Given a layer list, returns a list of layers directly connected to the top level node.


*Parameters*:

[source,python]
----
node = int or list
# A valid layer list or layer number.
array = list
# Top level calls of this function should pass an empty list.
----

*Returns*:
``array`` 

List of layers directly connected to the top level node - e.g. if the top level node specifies three layers in parallel (each of which has several layers in series), it will return the indices of each of the three parallel layers. If the node specifies two layers in series, it will return the first layer.

'''
==== _node{score}contains_ [[id,node_contains]]

Returns the number of a layer that is contained by the node given.


*Parameters*:

[source,python]
----
node = int or list
# A valid layer list or layer number.
----

*Returns*:
``val`` 

Int representing a layer number that is contained by this node.

'''
==== _series{score}equation_ [[id,series_equation]]

Returns the number of a layer that is contained by the node given.


*Parameters*:

[source,python]
----
a = int or list(int)
# The first layer set to be connected.
b : int or list(int)
# The second layer set to be connected. a != b
N : int
#The total number of layers. N > a,b
----

*Returns*:
``series`` 

List of length 3×N that specifies a series connection. First N entries are the coefficients multiplied by I~1~ to I~N~, and the next 2×N entries are the coefficients to be multiplied by K~1T~ through K~NB~. The right hand side of the equation is assumed to be zero.

'''
==== _faraday{score}equation_ [[id,faraday_equation]]

Generates a list representing a Faraday Loop taken between layer numbers a and b.


*Parameters*:

[source,python]
----
a = int or list(int) # if the latter, len(list) must equal 1 
# The first layer in the Faraday loop.
b = int or list(int) # if the latter, len(list) must equal 1 
# The second layer in the Faraday loop. a != b.
N = int
# The total number of layers. N > a, b.
d = float
# Skin depth 
bOverL = float
# Ratio of layer width to turn length.
r = float or float list
# Distances between layers. Can either be a single value (in which case distances are assumed to be the same) or a list of floats with N-1 entries.
N_turns = list(int)
# Number of turns of each layer. Should have N entries. If not specified, all layers will be assumed to have 1 layer each.
----

*Returns*:
``faraday`` 

List of length 3×N that specifies a Faraday loop. First N entries are the coefficients multiplied by I~1~ to I~N~, and the next 2×N entries are the coefficients to be multiplied by K~1T~ through K~NB~. The right hand side of the equation is assumed to be zero.

'''


