:tilde: ~
= Installation

This file explains how to download the current-sharing web GUI (along with the backend processing) and get a development mode instance running. This is fine for local use, but for professional use or to host an instance of this program for others, you will want to get a production mode instance running. *The latter* will be described in full detail later in an update once development is finished.

Below are Python libraries that this program will need. *Do not install Flask at this point -- this will be done in a later step.* The internal dependencies will come with a default install of Python 3, and thus do not need to be (and cannot be) reinstalled.

== Dependencies 

=== Internal Dependencies

* math
* decimal 
* time
* multiprocessing
* pprint

=== External Dependencies 

* Flask (*again, don't install this before proceeding to the next section*)
** Werkzeug
** MarkupSafe
** Click
** ItsDangerous

* NumPy
* SciPy
* SymPy
* pandas
* more_itertools

== Next Steps

Once all of these dependencies are installed, clone this GitHub repository. In the command line, perform a change directory operation (cd) into the folder into which the Git repository has been cloned. For example, on Linux, if you cloned flask-current into your home directory (:tilde:): 

....
cd ~/flask-current
....

Once that's done, create a virtual environment in Python and then activate it. 

....
$ python3 -m venv venv 
$ . venv/bin/activate
....

In this environment, install Flask. Then, exit the virtual environment.  

....
pip install Flask
deactivate
....

At this point, simply run the startup script (run.sh) and the Flask server will start. By default, the page will be hosted at localhost:5000, so go there. 
