:tilde: ~
= Installation

This file explains how to download the current-sharing web GUI (along with the backend processing) and get a development mode instance running. This is fine for local use, but for professional use or to host an instance of this program for others, you will want to get a production mode instance running. *The latter* will be described in full detail later in an update once development is finished.

To grab the code to work with from the very beginning, you would need to clone or download the Git source code. You can either do this in your terminal (shown below) or download the .ZIP file into a workspace of your choice from the GitHub page for this repository: 

....
git clone https://github.com/abhijeet-b/current-sharing.git
....

To see how to install the software for your operating system, jump to your operating system's section below. 



* <<Linux,Linux>>
* <<Mac,Mac OS X>>
* <<Windows,Windows>>

== Linux [[linux]]

Your distro likely comes with Python 3. If it doesn't, make sure to install it using the instructions for your distro and/or package manager.

Also important is making sure you have pip installed for Python 3. A good resource to find out how to install pip is <<here,https://packaging.python.org/en/latest/guides/installing-using-linux-tools/#installing-pip-setuptools-wheel-with-linux-package-managers>>.


== Mac OS X [[Mac]]

== Windows [[Windows]]