:tilde: ~
=== Assumptions

In all discussions to "change directories", this refers directly to the 'cd' command. This command, in any terminal/shell discussed in the operating systems below, allows you to change the folder you're working in in the terminal, which allows you to interact with the files of each folder as will be done in this guide. To keep track of which folders you can switch into or which files are in your present folder, the 'ls' or 'dir' commands (the former for Mac/Linux, the latter for Windows) are useful.

= Installation

As mentioned in the readme, Python 3 is the only consistent requirement no matter your choice of OS to install quickSHiFT on. This page aims to explain every step of the installation process to reproduce a working install of the program. This guide covers the installation processes on Windows, Mac OS X, and Linux.footnote:[For as popular as FreeBSD is as a server OS choice, an install of quickSHiFT has not been tested and thus will not be featured on this guide.]

*A quick note before proceeding further*

This file explains how to download the quickSHiFT web GUI (along with the backend processing) and get a *development mode* instance running. This is fine for local use, but for professional use or to host an instance of this program for others, you will want to get a *production mode* instance running. 

This is not only certainly possible, but also extremely important if deploying this code consistently on a large scale, such as on a VPS intended on handling significant amounts of traffic. Unfortunately, the steps to do this are beyond the scope of these instructions, as they require additional module installs and tool configurations that revolve around much more than merely getting a working instance on one machine. That said, https://flask.palletsprojects.com/en/2.1.x/deploying/[these] https://flask.palletsprojects.com/en/2.1.x/tutorial/deploy/[pages] are excellent resources with steps on how to do this, as well as recommendations for server applications and platforms that may fit your needs.

*Downloading the code*

To grab the code to work with from the very beginning, you would need to clone or download the Gitfootnote:[Instructions to install Git version control are https://git-scm.com/downloads[here].] source code. You can either do this in your terminal (shown below) or download the .ZIP file into a workspace of your choice from the GitHub page for this repository: 

....
git clone https://github.com/Power-Electronics-and-Magnetics-Group/quickshift.git
....

If you have a https://subversion.apache.org/[Subversion] client, you can also do:


....
svn checkout https://github.com/Power-Electronics-and-Magnetics-Group/quickshift.git
....


To see how to install the software for your operating system, jump to your operating system's section below. 



* <<Linux,Linux>>
* <<Mac,Mac OS X>>
* <<Windows,Windows>>

== Linux [[linux]]

Your distro likely comes with Python 3. If it doesn't, make sure to install it using the instructions for your distro and/or package manager.

Also important is making sure you have pip installed for Python 3. A good resource to find out how to install pip is https://packaging.python.org/en/latest/guides/installing-using-linux-tools/#installing-pip-setuptools-wheel-with-linux-package-managers[here].

If your distro is not included or you want to install pip directly, click on https://bootstrap.pypa.io/get-pip.py[this link] to download the pip installer and save it. Open the terminal of your choice, change directories into where the file was downloaded (only if you need to) and run: 

[source,shell]
....
python3 get-pip.py 
....

If there are instructions, follow them and pip should be installed. 

Once you're at a point when both Python 3 and pip are installed, install the following external dependencies for Python using pip:

* Flask
* numpy
* scipy
* sympy
* pandas
* more_itertools

To install all of them in one command, copy this command and paste it into your terminal of choice:

[source,shell]
....
python3 -m pip install Flask numpy scipy sympy pandas more_itertools
....

Next, you'll want to create a virtual environment in your local quickSHiFT folder to install Flask in. Change directories into where you downloaded/cloned the quickSHiFT folder and create a virtual environment: 

[source,shell]
....
cd quickshift
python3 -m venv venv
....

Activate the virtual environment using the command 

[source,shell]
....
. venv/bin/activate
....

Inside the virtual environment, install Flask once more and then exit: 

[source,shell]
....
python3 -m pip install Flask
deactivate
....

Lastly, you'll want to make sure the run script is executable. After this point, run it. By default, Flask opens a website instance at localhost:5000, so go there in the web browser of your choice.

[source.shell]
....
chmod +x run.sh
./run.sh
....


== Mac OS X [[Mac]]

There are relatively few differences between installing quickSHiFT on Linux and on Mac OS X. This is because Mac OS X is based on Unix and allows shell scripts to run in roughly the same way. You can follow the instruction guide above, but the one big difference is how you acquire Python 3 (and thus pip). 

Python 3 is _not_ built into Mac OS X -- only Python 2 is. Flask requires Python 3, so you will need to install Python 3 separately -- either through https://brew.sh/[Homebrew] or through the https://www.python.org/downloads/macos/[installer on the Python website]. 

Once done, you will need to download pip. Click on https://bootstrap.pypa.io/get-pip.py[this link] to download the pip installer and save it. Go into your Terminal, change directories into where the file was downloaded (only if you need to) and run: 

[source,shell]
....
python3 get-pip.py 
....

If there are instructions, follow them and pip should be installed.

At this point, you should be able to follow through the <<Linux,Linux>> guide with no issues.


== Windows [[Windows]]

Before proceeding further, make sure to install https://git-scm.com/download/win[Git for Windows]. This allows you to actually clone the repository in the git command line (if you really need to -- plus it speeds up pulling new updates to the code).

You will also need to download pip. Click on https://bootstrap.pypa.io/get-pip.py[this link] to download the pip installer and save it. Go into your Command Prompt or PowerShell, change directories into where the file was downloaded (only if you need to) and run: 

[source,shell]
....
python3 get-pip.py 
....

If there are instructions, follow them and pip should be installed. Then, install the following external dependencies that the quickSHiFT relies on. 

* Flask
* numpy
* scipy
* sympy
* pandas
* more_itertools

To install all of them in one command, copy this command and paste it into your terminal of choice:

[source,shell]
....
python3 -m pip install Flask numpy scipy sympy pandas more_itertools
....

Next, you'll want to create a virtual environment in your local quickSHiFT folder to install Flask in. Change directories into where you downloaded/cloned the quickSHiFT folder and create a virtual environment: 

[source,shell]
....
cd quickshift
python3 -m venv venv
....

Activate the virtual environment using the command 

[source,shell]
....
. venv/Scripts/activate
....

Inside the virtual environment, install Flask once more and then exit: 

[source,shell]
....
python3 -m pip install Flask
deactivate
....

Lastly, run the shell script 'run.bat'. It should be executable straight out of the gate, so you can either double click on it in File Explorer (where the quickSHiFT folder is located) or launch it in your shell as such:

[source.shell]
....
.\run.bat
....

Flask opens a website instance by default at localhost:5000, so go there in the web browser of your choice. 
