:tilde: ~
= Installation

This file explains how to download the current-sharing web GUI (along with the backend processing) and get a development mode instance running. This is fine for local use, but for professional use or to host an instance of this program for others, you will want to get a production mode instance running. *The latter* will be described in full detail later in an update once development is finished.

To grab the code to work with from the very beginning, you would need to clone or download the Git source code. You can either do this in your terminal (shown below) or download the .ZIP file into a workspace of your choice from the GitHub page for this repository: 

....
git clone https://github.com/abhijeet-b/current-sharing.git
....

To see how to install the software for your operating system, jump to your operating system's section below. 



* <<Linux,Linux>>
* <<Mac,Mac OS X>>
* <<Windows,Windows>>

== Linux [[linux]]

Your distro likely comes with Python 3. If it doesn't, make sure to install it using the instructions for your distro and/or package manager.

Also important is making sure you have pip installed for Python 3. A good resource to find out how to install pip is https://packaging.python.org/en/latest/guides/installing-using-linux-tools/#installing-pip-setuptools-wheel-with-linux-package-managers[here].

Once you're at a point when both Python 3 and pip are installed, install the following external dependencies for Python using pip:

* Flask
* numpy
* scipy
* sympy
* pandas
* more_itertools

To install all of them in one command, copy this command and paste it into your terminal of choice:

[source,shell]
....
python3 -m pip install Flask numpy scipy sympy pandas more_itertools
....

Next, you'll want to create a virtual environment in your local current-sharing folder to install Flask in. Change directories into where you downloaded/cloned the current-sharing folder and create a virtual environment: 

[source,shell]
....
cd current-sharing
python3 -m venv venv
....

Activate the virtual environment using the command 

[source,shell]
....
. venv/bin/activate
....

Inside the virtual environment, install Flask once more and then exit: 

[source,shell]
....
python3 -m pip install Flask
deactivate
....

Lastly, you'll want to make sure the run script is executable. After this point, run it. By default, Flask opens a website instance at link:localhost:5000[localhost:5000], so go there in the web browser of your choice.

[source.shell]
....
chmod +x run.sh
./run.sh
....


== Mac OS X [[Mac]]

== Windows [[Windows]]